version: '3'
services:

  dataclass-map-and-log:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: dataclass-map-and-log
    entrypoint: "poetry run pytest"
    tty: false
    working_dir: /app
    volumes:
      - ./:/app
